# Generated by Django 2.1.3 on 2018-11-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_offer_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
