# Generated by Django 2.1.3 on 2018-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_offer_offer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
