# Generated by Django 2.1.3 on 2018-11-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181127_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
